#!/usr/bin/env php
<?php


echo "Running tests.. ";
exec('vendor/bin/phpunit tests', $output, $returnCode);
echo PHP_EOL . implode($output, PHP_EOL) . PHP_EOL;
if ($returnCode !== 0) {
  echo "Aborting commit.." . PHP_EOL;

  sleep(2);
  exit(1);
}


sleep(1);


echo PHP_EOL.PHP_EOL."Running phpstan with level 5..." .PHP_EOL.PHP_EOL;
sleep(1);
exec('docker run -v $PWD:/app --rm phpstan/phpstan analyse src tests --level=5', $output2, $returnCode2);
echo PHP_EOL . implode($output2, PHP_EOL) . PHP_EOL;
if ($returnCode2 !== 0) {
  // Show full output
  echo "Aborting commit.." . PHP_EOL;

  sleep(2);
  exit(1);
}


sleep(2);
exit(0);


sleep(1);
echo PHP_EOL.PHP_EOL."Optionally running phpstan with level 8.. " .PHP_EOL.PHP_EOL;
sleep(1);
exec('docker run -v $PWD:/app --rm phpstan/phpstan analyse tests --level=8', $output3);
echo PHP_EOL . implode($output3, PHP_EOL) . PHP_EOL;


sleep(2);
exit(0);
